services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: sistema_chamados
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

  app:
    build:
      context: .
      dockerfile: dockerfile 
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db