services:

  ##parte que define o conteiner do banco de dados
  db:
  ##define a imagem oficial que será usada no projeto
    image: mysql:8.0
    restart: always

    ##variaveis do banco
    environment:
    ##nome do banco de dados
      MYSQL_DATABASE: sistema_chamados
      ##senha do banco
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
      ##mapeia o arquivo database.sql para a pasta dentro do docker, com isso ele executa scripts automaticamente quando o banco sobe pela primeira vez
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql


##conteiner da aplicação
  app:

  ##criação da imagem usando o arquivo dockerfile da mesma pasta
    build:
      context: .
      dockerfile: dockerfile 
    ports:
      - "8080:80" ##mapeia a porta 8080 do computador para a 80 do conteiner
    volumes:
      - ./:/var/www/html
    depends_on: ##comando para garantir que o conteiner da aplicação só suba depois do banco
      - db